
stages:
  - test
  - deploy

test-all:
    stage: test
    tags: [maven]
    except:
      - master
    script:
      - mvn clean install

test-unit:
  - stage: test
    tags: [maven]
    only:
      - master
    script:
      - mvn clean package
      - cp target/backend-social-network*.jar backend-social-network-${CI_COMMIT_SHA}.jar
    artifacts:
      name: backend-social-network
      expire_in: 1 week
      paths:
        - backend-social-network-${CI_COMMIT_SHA}.jar

deploy:
  stage: deploy
  needs: [test-unit]
  only:
    - master
  script:
    - ls backend-social-network*.jar