name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp-target/triangleTestExercise-1.0-SNAPSHOT.jar triangleTestExercise-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: triangleTestExercise
          path: triangleTestExercise-${{ github.sha }}.jar

  fake deploy:
      -runs on: self-hosted
      needs: run-unit-tests
      steps:
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: triangleTestExercise

      - name: Fake deploy
        run: ls triangleTestExercise*.jar